config/routes.rb
Ijustfarted::Application.routes.draw do
  resources :farts

  root :to => 'farts#index'

end

app/models/fart.rb
class Fart
  # attr_accessible :title, :body
  include Mongoid::Document
  include Mongoid::Timestamps
  include Geocoder::Model::Mongoid


  field :domain
  field :address
  field :latitude
  field :longitude
  field :coordinates, type: Array
  geocoded_by :address

  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/farts_controller.rb
class FartsController < ApplicationController
  # GET /farts
  # GET /farts.json
  def index
    @farts = Fart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @farts }
    end
  end

  # GET /farts/1
  # GET /farts/1.json
  def show
    @fart = Fart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fart }
    end
  end

  # GET /farts/new
  # GET /farts/new.json
  def new
    @fart = Fart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fart }
    end
  end

  # GET /farts/1/edit
  def edit
    @fart = Fart.find(params[:id])
  end

  # POST /farts
  # POST /farts.json
  def create
    @fart = Fart.new(params[:fart])

    respond_to do |format|
      if @fart.save
        format.html { redirect_to @fart, notice: 'Fart was successfully created.' }
        format.json { render json: @fart, status: :created, location: @fart }
      else
        format.html { render action: "new" }
        format.json { render json: @fart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /farts/1
  # PUT /farts/1.json
  def update
    @fart = Fart.find(params[:id])

    respond_to do |format|
      if @fart.update_attributes(params[:fart])
        format.html { redirect_to @fart, notice: 'Fart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farts/1
  # DELETE /farts/1.json
  def destroy
    @fart = Fart.find(params[:id])
    @fart.destroy

    respond_to do |format|
      format.html { redirect_to farts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/farts_helper.rb
module FartsHelper
end

app/views/farts/_form.html.erb
<%= form_for(@fart) do |f| %>
  <% if @fart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fart.errors.count, "error") %> prohibited this fart from being saved:</h2>

      <ul>
      <% @fart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/farts/edit.html.erb
<h1>Editing fart</h1>

<%= render 'form' %>

<%= link_to 'Show', @fart %> |
<%= link_to 'Back', farts_path %>

app/views/farts/index.html.erb
<div id="title" class="well well-small above-map">
  <h1>Global Farts</h1>
</div>

<div id="search-box" class="sidebar above-map">
  <form class="form-search">
    <input id="search" class="search-query" type="text">
  </form>
</div>

<div id="map_canvas"></div>

app/views/farts/new.html.erb
<h1>New fart</h1>

<%= render 'form' %>

<%= link_to 'Back', farts_path %>

app/views/farts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_fart_path(@fart) %> |
<%= link_to 'Back', farts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ijustfarted</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=visualization" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div> <!-- /container -->
</body>
</html>